name: Deploy Nginx with Docker to AWS EC2

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build -t nginx-app .

    - name: Login to AWS (EC2 Instance)
      uses: webfactory/create-ssh-key@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # Set your private key in GitHub secrets

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@54.169.129.16 << 'EOF'
          docker pull nginx-app
          docker stop nginx || true
          docker rm nginx || true
          docker run -d -p 80:80 --name nginx nginx-app
        EOF
