- name: Deploy to EC2 and Run Docker Container
  run: |
    ssh -o StrictHostKeyChecking=no -i ~/.ssh/ecs_key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
      # Ensure Docker is running on EC2
      sudo systemctl start docker || echo "Docker already running"

      # Remove any previous instance of the container
      docker stop nginx-app || true
      docker rm nginx-app || true

      # Create app directory and copy application files to EC2
      mkdir -p ~/app

      # Run SCP to copy files from GitHub runner to EC2 instance
      scp -o StrictHostKeyChecking=no -i ~/.ssh/ecs_key.pem -r * ubuntu@${{ secrets.EC2_PUBLIC_IP }}:~/app

      # Build and run the Docker container directly on EC2
      cd ~/app
      docker build -t nginx-app .
      docker run -d -p 80:80 --name nginx-app nginx-app
    EOF
  env:
    EC2_PUBLIC_IP: 3.0.175.228


