name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t nginx-app .

    - name: Prepare SSH key for EC2
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > ~/.ssh/ecs_key.pem
        chmod 600 ~/.ssh/ecs_key.pem

    - name: Deploy to EC2 and Run Docker Container
      run: |
        # SSH into the EC2 instance
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/ecs_key.pem root@54.254.205.59 << 'EOF'
          # Ensure Docker is running on EC2
          sudo systemctl start docker || echo "Docker already running"

          # Remove any previous instance of the container
          docker stop nginx-app || true
          docker rm nginx-app || true

          # Create app directory
          mkdir -p ~/app

          # Build and run the Docker container
          cd ~/app
          docker build -t nginx-app .
          docker run -d -p 80:80 --name nginx-app nginx-app
        EOF
      env:
        EC2_PUBLIC_IP: 54.254.205.59
